# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: mariusbertram
name: oci
version: 0.1.0
readme: README.md
authors:
  - Marius Bertram (github.com/mariusbertram)
description: Push and pull OCI Artefacts
license_file: LICENSE
tags:
# tags so people can search for collections https://galaxy.ansible.com/search
# tags are all lower-case, no spaces, no dashes.
  - oci
repository: https://github.com/mariusbertram/oci
#documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://github.com/mariusbertram/oci
issues: https://github.com/mariusbertram/oci/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
